apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: helloworld
    name: helloworld
    selfLink: /api/v1/namespaces/default/services/helloworld
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 32507
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: helloworld
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: null
    generation: 1
    labels:
      app: helloworld
    name: helloworld
    selfLink: /apis/apps/v1/namespaces/default/deployments/helloworld
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: helloworld
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: helloworld
      spec:
        containers:
        - image: tutum/hello-world
          imagePullPolicy: Always
          name: hello-world
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
