apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: limit-range
spec:
  limits:
  - max:
      cpu: 1
      memory: 300M 
    min:
      cpu: 0.5
      memory: 100M
    type: Container