kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: dev-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions","apps"]
  resources: ["*"]
  verbs: ["*"]

#   verbs: ["get", "list", "watch"]