apiVersion: v1
kind: Pod
metadata:
  name: soft-limit
spec:
  containers:
  - name: soft-limit
    image: hande007/stress-ng  
    args:
    - --vm-keep
    - --vm-bytes
    - 2g
    - --timeout
    - 600s
    - --vm
    - "1"
    - --oomable
    - --verbose    
    resources:
      requests:
        cpu: 500m
        memory: 1G