apiVersion: v1
kind: Pod
metadata:
  name: hard-limit
spec:
  containers:
  - name: hard-limit
    image: hande007/stress-ng
    args:
    - --vm-keep
    - --vm-bytes
    - 512m
    - --timeout
    - 600s
    - --vm
    - "1"
    - --oomable
    - --verbose        
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 256m
        memory: 1G