apiVersion: apps/v1
kind: Deployment
metadata:
  name: $EKS_DEPLOYMENT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      name: $EKS_DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        name: $EKS_DEPLOYMENT_NAME
    spec:
      containers:
      - name: $EKS_DEPLOYMENT_NAME
        image: $DEPLY_IMAGE
        ports:
        - containerPort: 3000