apiVersion: v1
kind: List
items:
- apiVersion: scheduling.k8s.io/v1
  kind: PriorityClass
  metadata:
    name: high-priority
  value: 100
  globalDefault: false
  description: "High-priority Pods"
- apiVersion: scheduling.k8s.io/v1
  kind: PriorityClass
  metadata:
    name: low-priority
  value: 50
  globalDefault: false
  description: "Low-priority Pods"  