apiVersion: v1
kind: Pod
metadata:
  name: pod-with-limit
  namespace: limit-range
spec:
  containers:
  - name: limit
    image: hande007/stress-ng  
    args:
    - --vm-keep
    - --vm-bytes
    - 2g
    - --timeout
    - 600s
    - --vm
    - "1"
    - --oomable
    - --verbose    
    resources:
      limits:
        cpu: 300m
        memory: 400M