apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  # Uncomment following line for fargate
  # namespace: fargate
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Uncomment to Share the Ingress across multiple ingress points
    # alb.ingress.kubernetes.io/group.name: <my-group>
    # alb.ingress.kubernetes.io/group.order: <'10'>
    # Uncomment following line for fargate
    # alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80