apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl-upg
  region: ap-south-1

managedNodeGroups:
- name: t3-managed-ng
  instanceType: t3.large
  minSize: 2
  maxSize: 4
  desiredCapacity: 2
  privateNetworking: true
  instancePrefix: eks-mng
  instanceName: prod-app
  labels: {role: worker,type: managed}  
  ssh:
    allow: true
    publicKeyName: eksworkshop
  tags:
    nodegroup-role: t3-worker
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoScaler: true
      externalDNS: true
      certManager: true
      appMesh: true
      appMeshPreview: true
      ebs: true
      fsx: true
      efs: true
      albIngress: true
      xRay: true
      cloudWatch: true