apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: uipl17
  region: ap-south-1

nodeGroups:
  - name: t3-spot-ng
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    instancePrefix: eks-spot
    instanceName: prod-app
    labels: {role: worker,type: spot} 
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3.small", "t3.medium","t3.large"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: capacity-optimized # launch Spot Instances from the most availably Spot Instance pools

