apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl-upg
  region: ap-southeast-1

nodeGroups:
  - name: t3-spot-ng
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    instancePrefix: eks-spot
    instanceName: prod-app
    labels: {role: worker,type: spot} 
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 2


